// Generated by Wrangler by running `wrangler types`

interface Env {
	CLOUDFLARE_ACCOUNT_ID: string;
	CLOUDFLARE_API_TOKEN: string;
	R2_BUCKET: R2Bucket;
	DB: D1Database;
	VECTORIZE: VectorizeIndex;
	AI: Ai;
}
